deployment:
  tasks:
    - export DEPLOYPATH=/home/offshorereactjs/public_html/
    - /bin/cp offshore $DEPLOYPATH
    # - /bin/cp style.css $DEPLOYPATH


  #   deployment:
  # tasks:
  #   - export DEPLOYPATH=/home/example/public_html/
  #   - /bin/cp -R images $DEPLOYPATH